<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="MAIN" Id="{500e18b9-5408-4d9f-adda-d2a5f4f3009f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	MyVar AT%I*:UDINT;
	StatusWordDrive2 AT%I*:UINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>