<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="MAIN" Id="{48bfe0e8-d73d-4fdd-873f-80e4de83eb30}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bVariableToLink  AT %I* : BOOL;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>